alpha: 0.4
batch_size_test: 32
batch_size_train: 8
bert_config: ../configs/config_bert.json
distill: true
embed_dim: 256
image_res: 384
image_root: ../images/RSTPReid/
k_test: 256
momentum: 0.995
optimizer: {lr: 1e-05, opt: adamW, weight_decay: 0.02}
queue_size: 65536
schedular: {cooldown_epochs: 0, decay_rate: 1, epochs: 30, lr: 1e-05, min_lr: 1e-06,
  sched: cosine, warmup_epochs: 1, warmup_lr: 1e-05}
temp: 0.07
vision_width: 768
warm_up: true
